language: node_js
branches:
  only:
    - master
    - develop
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
# - npm run coveralls
