export const sizeConversionOptions = [
  {
    mm: 44,
    in: 1.74,
    'us-can': '3',
    'uk-aus-sa': 'F ½',
    fr: 44,
    'in-cn-jp-sa-etc': 4,
  },
  {
    mm: 45,
    in: 1.78,
    'us-can': '3 ½',
    'uk-aus-sa': 'G',
    fr: 45,
    'in-cn-jp-sa-etc': 5,
  },
  {
    mm: 46,
    in: 1.82,
    'us-can': '3 ¾',
    'uk-aus-sa': 'H',
    fr: 46,
    'in-cn-jp-sa-etc': 6,
  },
  {
    mm: 47,
    in: 1.86,
    'us-can': '4',
    'uk-aus-sa': 'H ½',
    fr: 47,
    'in-cn-jp-sa-etc': 7,
  },
  {
    mm: 48,
    in: 1.89,
    'us-can': '4 ½',
    'uk-aus-sa': 'I ½',
    fr: 48,
    'in-cn-jp-sa-etc': 8,
  },
  {
    mm: 49,
    in: 1.93,
    'us-can': '4 ¾',
    'uk-aus-sa': 'J ½',
    fr: 49,
    'in-cn-jp-sa-etc': 9,
  },
  {
    mm: 50,
    in: 1.97,
    'us-can': '5 ¼',
    'uk-aus-sa': 'K',
    fr: 50,
    'in-cn-jp-sa-etc': 10,
  },
  {
    mm: 51,
    in: 2.01,
    'us-can': '5 ¾',
    'uk-aus-sa': 'L',
    fr: 51,
    'in-cn-jp-sa-etc': 11,
  },
  {
    mm: 52,
    in: 2.05,
    'us-can': '6',
    'uk-aus-sa': 'L ½',
    fr: 52,
    'in-cn-jp-sa-etc': 12,
  },
  {
    mm: 53,
    in: 2.09,
    'us-can': '6 ¼',
    'uk-aus-sa': 'M ½',
    fr: 53,
    'in-cn-jp-sa-etc': 13,
  },
  {
    mm: 54,
    in: 2.13,
    'us-can': '6 ¾',
    'uk-aus-sa': 'N ½',
    fr: 54,
    'in-cn-jp-sa-etc': 14,
  },
  {
    mm: 55,
    in: 2.17,
    'us-can': '7 ¼',
    'uk-aus-sa': 'O',
    fr: 55,
    'in-cn-jp-sa-etc': 15,
  },
  {
    mm: 56,
    in: 2.21,
    'us-can': '7 ½',
    'uk-aus-sa': 'P',
    fr: 56,
    'in-cn-jp-sa-etc': 16,
  },
  {
    mm: 57,
    in: 2.25,
    'us-can': '8',
    'uk-aus-sa': 'P ½',
    fr: 57,
    'in-cn-jp-sa-etc': 17,
  },
  {
    mm: 58,
    in: 2.29,
    'us-can': '8 ¼',
    'uk-aus-sa': 'Q ½',
    fr: 58,
    'in-cn-jp-sa-etc': 18,
  },
  {
    mm: 59,
    in: 2.33,
    'us-can': '8 ¾',
    'uk-aus-sa': 'R',
    fr: 59,
    'in-cn-jp-sa-etc': 19,
  },
  {
    mm: 60,
    in: 2.37,
    'us-can': '9',
    'uk-aus-sa': 'S',
    fr: 60,
    'in-cn-jp-sa-etc': 20,
  },
  {
    mm: 61,
    in: 2.41,
    'us-can': '9 ½',
    'uk-aus-sa': 'S ½',
    fr: 61,
    'in-cn-jp-sa-etc': 21,
  },
  {
    mm: 62,
    in: 2.45,
    'us-can': '10',
    'uk-aus-sa': 'T ½',
    fr: 62,
    'in-cn-jp-sa-etc': 22,
  },
  {
    mm: 63,
    in: 2.49,
    'us-can': '10 ¼',
    'uk-aus-sa': 'U ½',
    fr: 63,
    'in-cn-jp-sa-etc': 23,
  },
  {
    mm: 64,
    in: 2.52,
    'us-can': '10 ¾',
    'uk-aus-sa': 'V',
    fr: 64,
    'in-cn-jp-sa-etc': 24,
  },
  {
    mm: 65,
    in: 2.56,
    'us-can': '11',
    'uk-aus-sa': 'W',
    fr: 65,
    'in-cn-jp-sa-etc': 25,
  },
  {
    mm: 66,
    in: 2.6,
    'us-can': '11 ½',
    'uk-aus-sa': 'W ½',
    fr: 66,
    'in-cn-jp-sa-etc': 26,
  },
  {
    mm: 67,
    in: 2.64,
    'us-can': '11 ¾',
    'uk-aus-sa': 'X ½',
    fr: 67,
    'in-cn-jp-sa-etc': 27,
  },
  {
    mm: 68,
    in: 2.68,
    'us-can': '12 ¼',
    'uk-aus-sa': 'Z',
    fr: 68,
    'in-cn-jp-sa-etc': 28,
  },
  {
    mm: 69,
    in: 2.72,
    'us-can': '12 ½',
    'uk-aus-sa': 'Z ½',
    fr: 69,
    'in-cn-jp-sa-etc': 29,
  },
  {
    mm: 70,
    in: 2.76,
    'us-can': '13',
    'uk-aus-sa': '',
    fr: 70,
    'in-cn-jp-sa-etc': 30,
  },
  {
    mm: 71,
    in: 2.8,
    'us-can': '13 ¼',
    'uk-aus-sa': '',
    fr: 71,
    'in-cn-jp-sa-etc': 31,
  },
].map((o) => ({
  ...o,
  label: o['us-can'],
  value: o['us-can'],
  id: o.mm.toString(),
}))
